apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: nightblure/flask-k8s:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-lb-service
spec:
  type: LoadBalancer
  selector:
    app: flaskapp-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000