apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-lb-service
spec:
  type: LoadBalancer
  selector:
    app: flaskapp-deployment
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}